name: Build & Publish
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: Build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Verify Build Status
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

      # Pack
      - name: Pack
        run: dotnet pack Core.csproj --no-build --version-suffix $(git rev-parse --short "$GITHUB_SHA")
      
      # Publish
      - name: Publish NuGet
        run: dotnet nuget push Core.csproj --api-key ${{ secrets.NUGET_TOKEN_PRUSIAS }} --source https://api.nuget.org/v3/index.json

